get-message:
  handler: functions/send-message/index.handler
  iamRoleStatementsName: LambdaLexPermission-${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lex:RecognizeText
      Resource: "*"
  events:
    - http:
        path: /send-message
        method: get